# Generated by Django 4.2.7 on 2023-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='github_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='personal_url',
            field=models.URLField(null=True),
        ),
    ]
