# Generated by Django 4.2.7 on 2023-11-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_personalinfo_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='userID',
            new_name='user',
        ),
    ]
