# Generated by Django 4.2.7 on 2023-11-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_rename_userid_personalinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='user',
            new_name='users',
        ),
    ]
